name: workshoucbexplorer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^12.0.0
  mobile_scanner: ^7.0.0
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  flutter_gemini: ^2.0.3
  cupertino_icons: ^1.0.6
  google_generative_ai: ^0.2.2  
  qr_flutter: ^4.0.0
  firebase_storage: ^12.4.6
  path_provider: ^2.1.5




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
